### PR TITLE
Give Credit to taco wizard sprite

### PR DESCRIPTION
**Pull request by leahcimto**
### Resolves:
#212 

### Changes:
Adds credit for the taco wizard sprite.

I'm wondering if designerd should be credited. Thoughts on that?

### Local Tests:

None

### CODE REVIEW

**Comment by BarelySmooth** [comment]
You're right. Section 5.2 of the [Scratch Terms of Use](https://scratch.mit.edu/terms_of_use/) state that support materials are licensed under the Creative Commons Attribution-ShareAlike 2.0 license.

But why is it on the contributors page? If it was a 'Credits' page, then it could go there but the Taco Wizard sprite isn't a contributor (or a service). Also, the taco wizard isn't seen on the contributors page - and it can cause confusion. I think it should be mentioned in the 404 page itself.

**Comment by Shluffy** [comment]
> You're right. Section 5.2 of the [Scratch Terms of Use](https://scratch.mit.edu/terms_of_use/) state that support materials are licensed under the Creative Commons Attribution-ShareAlike 2.0 license.
> 
> But why is it on the contributors page? If it was a 'Credits' page, then it could go there but the Taco Wizard sprite isn't a contributor (or a service). I think it should be mentioned in the 404 page itself.

Shouldn't llk be mentioned.

> 5.2 Scratch provides support materials, including images, sounds, video, and sample code, to help users build projects. Support materials are licensed under the Creative Commons Attribution-ShareAlike 2.0 license. You may also use screenshots of Scratch under the same license. Please note that this does not apply to materials that are also trademarked by the Scratch Team or other parties as described in parts 5.4 and 5.5, below.
The Creative Commons Attribution-ShareAlike 2.0 license requires you to attribute any material you use to the original author. When you use Scratch support materials, or screenshots of the Scratch website, please use the following attribution: "Scratch is developed by the Lifelong Kindergarten Group at the MIT Media Lab. See http://scratch.mit.edu."

**Comment by Shluffy** [comment]
> I'm wondering if designerd should be credited. Thoughts on that?

probably not. we should just credit scratch

**Comment by Shluffy** [comment]
> > Shouldn't llk be mentioned.
> 
> About that, Scratch is now owned by the Scratch Foundation. I don't know why the Terms of Use say that.

isn't it still developed by Llk (see @llk)

**Comment by BarelySmooth** [comment]
> > > Shouldn't llk be mentioned.
> > 
> > 
> > About that, Scratch is now owned by the Scratch Foundation. I don't know why the Terms of Use say that.
> 
> isn't it still developed by Llk (see @LLK)

According to [the FAQ](https://scratch.mit.edu/info/faq), its a prject of the Scratch Foundation:

> We ask that you include a note somewhere in your materials saying: "Scratch is a project of the Scratch Foundation, in collaboration with the Lifelong Kindergarten Group at the MIT Media Lab. It is available for free at https://scratch.mit.edu".

The "Licensing and Permissions" section of the FAQ gives a pretty good idea of how we should credit.

**Comment by leahcimto** [comment]
> > > > Shouldn't llk be mentioned.
> > > 
> > > 
> > > About that, Scratch is now owned by the Scratch Foundation. I don't know why the Terms of Use say that.
> > 
> > 
> > isn't it still developed by Llk (see @LLK)
> 
> According to [the FAQ](https://scratch.mit.edu/info/faq), its a prject of the Scratch Foundation:
> 
> > We ask that you include a note somewhere in your materials saying: "Scratch is a project of the Scratch Foundation, in collaboration with the Lifelong Kindergarten Group at the MIT Media Lab. It is available for free at https://scratch.mit.edu".
> 
> The "Licensing and Permissions" section of the FAQ gives a pretty good idea of how we should credit.

Thanks, added.

**Comment by Shluffy** [comment]
Looks Pretty Good Now:
Screenshot 2021-06-08 1 48 48 PM
image

**Comment by leahcimto** [comment]
Hold on, don't merge. I'm putting some margin on it.

**Comment by leahcimto** [comment]
Margin added

**Review by Accio1 — APPROVED** [review]
Looks good! It seems like Taco Wizard is licenced under Creative Commons Attribution-ShareAlike, so crediting the creator (Scratch) is the proper way to credit.

**Pull request merged**
