### PR TITLE
ye

### PR DESCRIPTION
**Pull request by LankyBox01**
since i was accepted

### CODE REVIEW

**Comment by LankyBox01** [comment]
uhm
help

**Comment by MTM828** [comment]
lol

**Comment by Accio1** [comment]
We have to do a mass PR which adds everyone who has been accepted since the last person currently listed on the site. This PR is blocked pending that.

**Comment by leahcimto** [comment]
Yup. As Accio1 said, this is to be done in one large pull request. Closed per #78.

**Pull request closed without merging**
