### PR TITLE
Change File Paths

### LINKED ISSUE #14: Capitalisation in paths
I notice a commit stating "rename `quotes/` to `Quotes/`". It generally isn't aesthetically pleasing to use camelcase paths in URLs, nor to use underscores. I'd recommend renaming of all files back to lowercase, and using spaces (0x20 // %20) instead of underscores.

We can then address files at these locations via URI encoding (e.g. `theforumhelpers/forum%20helpers/` for the folder "forum helpers".

### PR DESCRIPTION
**Pull request by leahcimto**
Changes file paths to lowercase and underscores removed completely. Header updated to reflect these changes.

Resolves #14.

### CODE REVIEW

**Comment by Accio1** [comment]
Why is this a draft? Do changes still have to be made?

**Comment by leahcimto** [comment]
> Why is this a draft? Do changes still have to be made?

I was just testing if the links were working.

**Comment by Accio1** [comment]
The following tests were performed locally:
- [ ] Change folder names to reflect the new URL styles
- [ ] Change the actual relative links in each page to redirect to the page with the correct capitalization
- [ ] Do not change links to QuickReply. It is capitalized intentionally because it is the name of a specific tool (this may be changed in the future but not this update)
- [ ] Do a full run through checking each link to make sure it directs to the correct place

**Review by Accio1 — APPROVED** [review]
Good to merge! Thanks @leahcimto

**Comment by Accio1** [comment]
This broke the List of Forum Helpers page because the json files are still referenced as being under /Forum_Helpers. This wasn't caught locally because the links are hard coded and not relative.

**Comment by leahcimto** [comment]
> This broke the List of Forum Helpers page because the json files are still referenced as being under /Forum_Helpers. This wasn't caught locally because the links are hard coded and not relative.

Sorry for not checking that!

**Pull request merged**
