### PR TITLE
Increase padding for nav-links

### LINKED ISSUE #189: Feature Request: Increase padding for navbar links
**Is your feature request related to a problem?**
Yes. There isn't enough left and right padding between links in the navigation bar. Currently, it is only 5px.

**Describe alternatives you've considered**
Increase the padding to about 15px. Anywhere between 10px and 15px would be fine.

**Additional context**
Currently, it looks like this:
image

I tested it out with increased padding:
image

Another thing to consider is the max-width at which the site will switch to mobile view. 
```css
@media only screen and (max-width: 1100px) {
   ...
}
```
Here, ```max-width``` has to be increased. Changing it to ```1220px``` worked for me (with 15px padding).

### PR DESCRIPTION
**Pull request by BarelySmooth**
### Resolves:
Resolves #189 - Increase padding for navbar links 

### Changes:
Increased padding of navbar elements to 15px (to the right and left of each link).
Also changed the max-width when the site will switch to mobile view to 1220px so that the nav-bar links don't overflow.

### Local Tests:
I tested this using git locally (through localhost) and things worked fine.

### CODE REVIEW

**Review by leahcimto — APPROVED** [review]
Tested locally, and looks good. For me though, I kind of feel like 15px is a bit wide, and 10px looks better, but that's just my personal opinion so no need to change anything.

**Review by Accio1 — CHANGES_REQUESTED** [review]
@BarelySmooth the breakpoint seems a little too large now. It cuts before getting close to the header text. Do you think it could be reduced a little bit? I also agree with @leahcimto that 10px would probably be sufficient, as that would give a 20px gap between the text in each link.

**Comment by BarelySmooth** [comment]
I hope its fine now. Sorry for the extra commits, I messed up something when resolving a merge conflict :P

**Review by Accio1 — APPROVED** [review]
Looks good!

**Comment by Shluffy** [comment]
@Accio1 is this still changes requested

**Comment by leahcimto** [comment]
@Shluffy Changed

**Pull request merged**
