### PR TITLE
Rework the "List Of Forum Helpers" page to use JSON

### PR DESCRIPTION
**Pull request by Accio1**
-This update is focused on reworking the "List Of Forum Helpers" page in order to make it use JSON to display the list. This is better than the old system because it will be easier to add new Forum Helpers or modify existing Forum Helpers.

This was inspired by #15 but it has been reworked to use JavaScript instead of Jekyll.

Note: Biographies/users might not be up to date. This is intentional, because the JSON files were copied from #15 which was created several months ago. These biographies/missing users will be fixed in a later update after this pull request has been merged

### CODE REVIEW

**Comment by Accio1** [comment]
@Nambaseking01 
@NilsTheBest 
Both of you have been interested in this site in the past, so I would like if you could review this pull request before I merge it.

**Comment by Nambaseking01** [comment]
When LastContinue made the original pull request on this, I already thought it would be a good idea. Now that it's upgraded into JavaScript, it seems like a nice script!

Just a question - does the new way change the way that users get displayed?

**Comment by Accio1** [comment]
> When LastContinue made the original pull request on this, I already thought it would be a good idea. Now that it's upgraded into JavaScript, it seems like a nice script!
> 
> Just a question - does the new way change the way that users get displayed?

No, they look the exact same on the page, the only difference is that it's easier to add new users and alter existing users. Also, if we wanted to display them differently in the future, it would be much easier to do so because we would just have to edit the template once, instead of multiple times.

**Comment by Accio1** [comment]
Since you've approved the changes, I'm just waiting for @NilsTheBest, and then I can merge!

**Comment by Accio1** [comment]
Fantastic! Merging!

**Comment by Accio1** [comment]
Merged!

**Pull request merged**
