### PR TITLE
Relative URLs

### LINKED ISSUE #163: Feature Request: use relative urls
looking through the source code, there are so many places where stuff points to theforumhelpers.github.io. this makes development tedious. why not just use relative urls like
```js
fetch("/forumhelpers/"+dataSet+".json")
```

instead of

```js
fetch("https://theforumhelpers.github.io/forumhelpers/"+dataSet+".json")
```

another example of this was in #152 where some obscure `<base>` element was used when it could have just been as simple as adding a slash before the paths. like `<link rel="stylesheet" type="text/css" href="/resources/stylesheet.css">` instead of `<link rel="stylesheet" type="text/css" href="resources/stylesheet.css">`

is there a specific development reason not to? this will allow development to be so much easier.

### PR DESCRIPTION
**Pull request by BarelySmooth**
### Resolves:
Resolves #163 

### Changes:
Removes the `href` attribute in the `<base>` tag. I added some javascript code to automatically add the href attribute to the base tag after the page loads and before other elements load.

### Local Tests:
Yes, tested locally using `localhost` and `file://` urls

### Things to note
The code isn't complete yet. That is why this PR is a draft. Note that the code is completely functional but there are a lot of things I could do to organise it (right now, it looks like a mess, sorry). I put a script tag at the top (and that was intentional because it had to load before other elements did). Also, I used script tags to add the JS code to `404.html`. Let me know if I should change that

### CODE REVIEW

**Comment by Steve0Greatness** [comment]
looks nice! This will help local testing work easily on the 404 page.

**Comment by BarelySmooth** [comment]
@Accio1 I added a script tag to the top of the file, should I keep it there are add it to another file?

**Comment by Accio1** [comment]
> @Accio1 I added a script tag to the top of the file, should I keep it there are add it to another file?

I don't think it is worth the effort to add it to another file, especially since it is only used by the 404 page and isn't overly long.

**Comment by BarelySmooth** [comment]
> > @Accio1 I added a script tag to the top of the file, should I keep it there are add it to another file?
> 
> I don't think it is worth the effort to add it to another file, especially since it is only used by the 404 page and isn't overly long.

So, the script tag at the top would be fine there, right? Or should I move it to imports.js?

**Comment by Accio1** [comment]
> > > @Accio1 I added a script tag to the top of the file, should I keep it there are add it to another file?
> > 
> > 
> > I don't think it is worth the effort to add it to another file, especially since it is only used by the 404 page and isn't overly long.
> 
> So, the script tag at the top would be fine there, right? Or should I move it to imports.js?

Yes, I think keeping the script tag would be fine.

**Comment by BarelySmooth** [comment]
I've marked this as ready for review - earlier I thought I could make the code better over time, but I think this has been a draft for way too long 😅

**Comment by Accio1** [comment]
Sorry, I wasn't reviewing this because it was a draft and didn't realise you marked it ready for review. I'll get to reviewing it soon!

**Comment by Accio1** [comment]
This was what happened when I tested by deploying to GH Pages. 
image
It worked fine on file:/// but not when deployed.

The version I deployed is live at: https://accio1.github.io/theforumhelpers.github.io/404.html

**Comment by Steve0Greatness** [comment]
> @BarelySmooth
> This was what happened when I tested by deploying to GH Pages.
> image
> It worked fine on file:/// but not when deployed.
> 
> The version I deployed is live at: https://accio1.github.io/theforumhelpers.github.io/404.html

I think that happens because the base tag is set to `https://accio1.github.io` and not `https://accio1.github.io/theforumhelpers.github.io`

**Comment by BarelySmooth** [comment]
> I think that happens because the base tag is set to `https://accio1.github.io` and not `https://accio1.github.io/theforumhelpers.github.io`

That was quite intentional 😛 It should probably work when deployed to the main website here - since `window.location.origin` would be theforumhelpers.github.io in that case.

image

@Accio1 I think I can fix this, should I get started on it?

**Comment by Steve0Greatness** [comment]
@BarelySmooth that sound good, should be a quick fix.
1 check could be good:
```js
if (window.location.origin.includes('github.io') && window.location.origin != 'https://theforumhelpers.github.io') {
document.getElementsByTagName('base')[0].href = window.location.origin + 'theforumhelpers.github.io'
}
```
yeah, something like that(that might not even work tbh)

**Comment by BarelySmooth** [comment]
> @BarelySmooth that sound good, should be a quick fix.


I have another fix for this - but it can sometimes cause even more problems. Here is what I have in mind:
```js
// then it is being run either on localhost or on the website. Then the baseHref will be window.location.origin
// ...except it only works when it is deployed on the TFH website.
let path = window.location.host + window.location.pathname;
numberOfForwardSlashesInPath = findNumberOfForwardSlashes(path);

let i = 0;
let forwardSlashesUntilNow = 0;
while (forwardSlashesUntilNow < numberOfForwardSlashesInPath) {
	if (path[i] == '/') {
		forwardSlashesUntilNow++;
	}
	websitePath += path[i];
	i++;
}
console.log(websitePath)
websitePath = window.location.protocol + "//" + websitePath;
console.log(websitePath);
```

**Comment by gosoccerboy5** [comment]
Question - why do we need all this effort just for the 404 page? Honestly, I'm fine with having a little `<base>` tag, but if you guys don't like it that's fine I guess

**Comment by Steve0Greatness** [comment]
> Question - why do we need all this effort just for the 404 page? Honestly, I'm fine with having a little `<base>` tag, but if you guys don't like it that's fine I guess

I think it's mostly so that we don't have to edit the base tag whenever we make a fork.

**Comment by BarelySmooth** [comment]
> > I think that happens because the base tag is set to `https://accio1.github.io` and not `https://accio1.github.io/theforumhelpers.github.io`
> 
> That was quite intentional  It should probably work when deployed to the main website here - since `window.location.origin` would be theforumhelpers.github.io in that case.
> 
> image
> 
> @Accio1 I think I can fix this, should I push it?

bump (incase you missed it)

**Comment by Accio1** [comment]
@BarelySmooth yes, if you have a fix please push it.

**Comment by BarelySmooth** [comment]
> @BarelySmooth yes, if you have a fix please push it.

Done!

**Comment by Accio1** [comment]
Now the following link doesn't work:
https://accio1.github.io/theforumhelpers.github.io/404.html/

**Comment by BarelySmooth** [comment]
> Now the following link doesn't work because of the slash at the end of the URL:
> https://accio1.github.io/theforumhelpers.github.io/404.html/

Alright. I'll try fixing it.

**Comment by Accio1** [comment]
@BarelySmooth pinging you just in case you forgot about this. If you are too busy or have other obligations, that is completely fine and I will open up this issue for someone else to build off the code that you have already contributed.

**Comment by BarelySmooth** [comment]
> @BarelySmooth pinging you just in case you forgot about this. If you are too busy or have other obligations, that is completely fine and I will open up this issue for someone else to build off the code that you have already contributed.

Turns out this works on `file://` urls only on Windows, but not on macOS. I think it'll be better if someone else builds up on this. Thanks for the opportunity though 😃

**Comment by gosoccerboy5** [comment]
That was quite an interesting pull request :P (no offense)

**Pull request closed without merging**
