### PR TITLE
Make header title a link

### LINKED ISSUE #333: Feature Request: Make the “The Forum Helpers” text in the header also link to the hompage
I feel like that when on a page on the website, it is not obvious how to go back to the hompage. Usually, the name of the website in the hompage links to the hompage when clicked. I think it would be better and more intuitive to make it so that both the text (“The Forum Helpers”) and the icon link to the hompage.

Even better, when they (the icon and the text, as a whole) are hovered on, there will be a slight rounded background to show that clicking the icon or the text will do something.

I actually didn’t know how to go back to the hompage (other than using the browser’s back button) until today.

### PR DESCRIPTION
**Pull request by Accio1**
### Resolves:

Resolves #333 

### Changes:

- Make the title in the header a link by wrapping the <a> tag around it
- Make max-width of the header title 37.5% so that the link doesn't overflow the text

### Local Tests:

Tested locally

@penguinmoose this was your issue so feel free to review.

### CODE REVIEW

**Review by leahcimto — APPROVED** [review]
Tested locally, looks good!

**Comment by leahcimto** [comment]
I can't request @penguinmoose for review for some reason (I think it only shows editors) so I will just assign them.

**Comment by leahcimto** [comment]
@penguinmoose do you mind reviewing?

**Comment by penguinmoose** [comment]
@leahcimto I'm trying to, but I can't. It seems like I can only review if I have write access, which I don't. Any idea how I can review it?

**Review by penguinmoose — APPROVED** [review]
Ok, finally I can review it!

**I'm approving it.**

**Pull request merged**
