### PR TITLE
Better CSS, Navbar, Scrollbar, Etc

### PR DESCRIPTION
**Pull request by TheColaber**

### CODE REVIEW

**Comment by gosoccerboy5** [comment]
Meh, I see the current CSS as fine, compared to your changes.

**Comment by Accio1** [comment]
In the future, please create an issue and wait to be assigned before creating a PR. Additionally, these changes break the navbar on mobile, so they will not be implemented.

**Comment by TheColaber** [comment]
I mean there is already an issue on better css... Also, mobile worked fine for me... Not sure why you do this whole "assigning" thing, rather than letting others pr freely... Welp, I guess I better move along

**Comment by Accio1** [comment]
> I mean there is already an issue on better css... Also, mobile worked fine for me... Not sure why you do this whole "assigning" thing, rather than letting others pr freely... Welp, I guess I better move along

The issue you are referring to is labelled as "needs-discussion". This means that people need to contribute ideas and a plan needs to be formed before a PR is created. Waiting to be assigned ensures that adequate discussion has taken place so that the person creating the PR understands what it is they should be changing. If anyone could come along and "pr freely", then this site would be a mishmash of so many different things that it would look and function terribly. Hence the process of:

1. Issue is created
2. Issue is discussed if needed
3. A plan for how could be implemented is made
4. Someone is assigned
5. They create a PR
6. It gets reviewed
7. Changes are made if necessary
8. The PR is merged

This ensures that all code added to the site has been approved and reviewed properly. If you want to help contribute to the CSS of the site, I would recommend posting some ideas in #150 which is about updating the site CSS.

**Comment by TheColaber** [comment]
Well I think you should give it a try, because it seems you just focused on the negative. You can ofc reject prs, but my point is, the changes in these prs arent "mishmash". Other prs could be, which in that case you could close. And if you don't like a certain feature in this pr, you could just mention it. In fact, that's how successful os projects succeed. They don't reject a pr anytime they weren't expecting it. Anyway, I understand you have your way of things, so I'll leave you to it. Sorry for causing much inconvenience.

**Pull request closed without merging**
