### PR TITLE
Test Labeller #1

### PR DESCRIPTION
**Pull request by Accio1**
This PR changes index.html and curators.json . It should be labelled as unreviewed and Forum Helpers list

### CODE REVIEW

**Comment by leahcimto** [comment]
I would assume this failed?

**Comment by Accio1** [comment]
> I would assume this failed?

Yes, I'm testing out the labeler in a private repository now to see why.

**Comment by Accio1** [comment]
Closing and reopening so that it runs again

**Comment by Accio1** [comment]
@leahcimto the labeller is working!

**Comment by leahcimto** [comment]
Awesome!

**Pull request closed without merging**
