### PR TITLE
new curators and update managers

### PR DESCRIPTION
**Pull request by leahcimto**

### CODE REVIEW

**Comment by Accio1** [comment]
Please create a new JSON file called past.json and add fdreerf to that.

**Comment by leahcimto** [comment]
Will do

**Comment by leahcimto** [comment]
@Accio1 Created past.json, and promoted me and FloatingMuffins.

**Review by Accio1 — APPROVED** [review]
Looks good, I changed Ihatr's biography back to the one they submitted before just because the paradox that they made no longer works since they were moved to the managers section.

**Comment by leahcimto** [comment]
@Accio1 I give ihatr permission for his bio :P

**Comment by Accio1** [comment]
@leahcimto alright, I'll fix that in a lone commit in a few minutes.

**Comment by Accio1** [comment]
@leahcimto since you are now a manager, and because of your help with this repository, I've added you to the editors team. This means that you will have write access to the repository, and your reviews on pull requests will actually count as an editor review from now on. I think that this also means that you can create branches in this repository and commit to any branch except for master, which requires a pull request still. Congratulations and thanks again for all your help!

**Comment by leahcimto** [comment]
Thanks!

**Pull request merged**
