### PR TITLE
Fix CSS: Move Inline CSS | Part 2/4 of Fix CSS (#58)

### PR DESCRIPTION
**Pull request by leahcimto**
All inline CSS has been moved to the stylesheet. Part 2 of Fix CSS. All changes were tested locally on my PC.

### CODE REVIEW

**Comment by Accio1** [comment]
Taking a quick look at this without fully reviewing it, on the Forum Helpers page, the list of Forum Helpers is pushed further to the right than it should be. I'll try to find the cause within the next few days.

**Comment by leahcimto** [comment]
@Accio1 I'll look into that.

**Comment by leahcimto** [comment]
I can't seem to find the cause looking briefly over the stylesheet. Let me know if you find anything.

**Comment by Accio1** [comment]
I've found it, I will commit a fix today and then merge this hopefully today or over the weekend.

**Review by Accio1 — APPROVED** [review]
I submitted a small commit that fixed a few things. Good to merge now!

**Comment by leahcimto** [comment]
Great!

**Pull request merged**
