### PR TITLE
Fix CSS: Remove Duplicate CSS | Part 4/4 of Fix CSS (#56)

### PR DESCRIPTION
**Pull request by leahcimto**
Removes duplicate CSS from the stylesheet. I wasn't able to find a bunch, but I may have missed some.

Final part in Fix CSS. #56 
cc @Accio1

### CODE REVIEW

**Comment by Accio1** [comment]
I'm reviewing this locally to see if I can find any other changes that should be made. Looks good so far though.

**Review by Accio1 — APPROVED** [review]
I just made a few changes, looks good to merge now. Feel free to re-review @leahcimto just to make sure that the changes I have made make sense.

**Comment by leahcimto** [comment]
Looks good!

**Comment by leahcimto** [comment]
yay

**Pull request merged**
