### PR TITLE
cursor: pointer;

### LINKED ISSUE #187: Idle > Pointer
Make it so that when the mouse hoves over the "okay" and "leave site" button in the google analytics banner, it turns to a pointer
`cursor: pointer;`

### PR DESCRIPTION
**Pull request by CodeGuy92**
### Resolves:

Resolves #187

### Changes:

Pretty obvious. I had to remake the PR because apparently my fork was deleled.

### Local Tests:

Yup, seems to work fine. (I forgot to take screenshots oof)

### CODE REVIEW

**Comment by gosoccerboy5** [comment]
Hopefully this one is less of a mess than the last one :P

**Comment by CodeGuy92** [comment]
Yea, lol

**Review by leahcimto — APPROVED** [review]
Looks good


@Accio1 Good to merge

**Comment by CodeGuy92** [comment]
> Looks good
> 
> @Accio1 Good to merge

If this doesn't get merged by next week, i swear to god-

**Comment by Accio1** [comment]
> > Looks good
> > @Accio1 Good to merge
> 
> If this doesn't get merged by next week, i swear to god-

@CodeGuy92 Please appreciate that I have been very busy the past couple weeks working on completing my school year. This was not a priority, so that is why I didn't have time to review it. Please be patient.

**Review by Accio1 — APPROVED** [review]
Looks good!

**Comment by CodeGuy92** [comment]
finalyyyyyyyyyyyyyyyyyyyyyyyy

**Comment by Accio1** [comment]
Again, 

> @CodeGuy92 Please appreciate that I have been very busy the past couple weeks working on completing my school year. This was not a priority, so that is why I didn't have time to review it. Please be patient.

**Comment by CodeGuy92** [comment]
> Again,
> 
> > @CodeGuy92 Please appreciate that I have been very busy the past couple weeks working on completing my school year. This was not a priority, so that is why I didn't have time to review it. Please be patient.

uh... https://scratch.mit.edu/users/-Accio-/#comments-148474238

**Pull request merged**
