### PR TITLE
Improve Header and Footer

### LINKED ISSUE #64: Bug: margins on mobile
margins on small devices make reading content impossible

### LINKED ISSUE #114: Change the way that the header and footer is implemented.
Right now, the header and footer are embeds, meaning that it is very difficult to make changes to them or resize them, especially getting them to look good on a range of devices. Therefore, a better way to insert the header and footer into each page is needed. One way of doing this, which recently worked well for me on another site is by using JavaScript to insert the HTML directly into the page. The header and footer would be assigned as a variable in a JS file, which then would be loaded on each page and would insert the code into the corresponding part of the page. Since the code would then be a part of the page, it could easily be styled using CSS, and changing the JS file would change the header/footer for each page. This would allow issue #89 to be resolved, and would be a good step towards resolving #64 

@leahcimto thoughts?

### LINKED ISSUE #131: Bug: nav links redirect to this repository's version
**Describe the bug**
when you work on this repo locally or on a fork, when you click a nav button it redirects you to this repo's version instead of the local version.

**To Reproduce**
1. download a local version
2. open the homepage
3. press a nav button (not the studio one)
4. it redirects you to this repo's version and not the local version

**Expected behavior**
uses the local version for the nav links instead of this repo's version 

**Browser Information**
n/a

### PR DESCRIPTION
**Pull request by Accio1**
### Resolves:

Resolves #64
Resolves #114 
Should resolve #131 
Steps towards resolving #89 

### Changes:

- Header and footer are now stored in a js file which is loaded onto each page. This js inserts the header and footer onto the page when loaded. This will fix a lot of issues that have arisen from using embeds to insert the headers and footer (especially issues with sizing).
- On screens less than 1100px wide, (around the cutoff for iPads), the header title will start shrinking to fit within the header and the nav links will change into a dropdown. When this dropdown is hovered over (desktop) or clicked on (mobile), it will show the three header links below it.
    - There are still a few changes that might need to be made to the dropdown, but I wanted to get this released since it is mostly working.

### Local Tests:

Tested locally using chrome inspector tools to simulate the screen widths of different devices. I have attached screenshots below.

Desktop:
Desktop

iPad (collapsed):
iPad

iPad (expanded)
iPadE

iPhone X (collapsed):
iPhone

iPhone X (expanded):
iPhoneE

@leahcimto 

Note to reviewers: The best way to review this would probably be using the device dimensions simulator in chrome inspector tools to try to find dimensions that break the header.

### CODE REVIEW

**Comment by gosoccerboy5** [comment]
:warning:
Maybe you're planning on fixing this later, but 
Screen Shot 2021-05-08 at 2 34 18 PM
the footer CSS needs a little fixing. I'm sure you'd be able to do that after merging the PR

**Comment by Accio1** [comment]
> How did you make it detect screen width, and disable certain header elements, depending on that?

You can use CSS's built in feature of: @media only screen and (max-width: ). To see how it was used in this case, you can look on line 111 of the stylesheet.css that is changed in the PR.



> ⚠️
> Maybe you're planning on fixing this later, but
> Screen Shot 2021-05-08 at 2 34 18 PM
> the footer CSS needs a little fixing. I'm sure you'd be able to do that after merging the PR

Which device/browser are you using? That doesn't happen to me.

**Comment by gosoccerboy5** [comment]
> > How did you make it detect screen width, and disable certain header elements, depending on that?
> 
> You can use CSS's built in feature of: @media only screen and (max-width: ). To see how it was used in this case, you can look on line 111 of the stylesheet.css that is changed in the PR.

Oh, awesome!

> > How did you make it detect screen width, and disable certain header elements, depending on that?
> 
> You can use CSS's built in feature of: @media only screen and (max-width: ). To see how it was used in this case, you can look on line 111 of the stylesheet.css that is changed in the PR.
> Which device/browser are you using? That doesn't happen to me.

Firefox 88.0.1, MacOS Big Sur 11.3
Maybe it's a problem on my end

**Comment by Accio1** [comment]
> > Which device/browser are you using? That doesn't happen to me.
> 
> Firefox 88.0.1, MacOS Big Sur 11.3
> Maybe it's a problem on my end

Huh, seems to be a Firefox problem because it isn't happening when I use Chrome. I'll try to do a bit of digging and see why this might be happening.

**Review by leahcimto — COMMENTED** [review]
Woah! That's really cool! Before I approve this, I noticed that when you shrink down your window that has the tab open, the header collapses (expected) but it's really hard to click on a link after you hover over the menu button. Should this be fixed?

**Comment by Accio1** [comment]
> Woah! That's really cool! Before I approve this, I noticed that when you shrink down your window that has the tab open, the header collapses (expected) but it's really hard to click on a link after you hover over the menu button. Should this be fixed?

Thanks for catching that. I had implemented a fix that was working but now it isn't any more so I might have changed something on accident. I'll try to fix that now.

**Comment by Accio1** [comment]
@leahcimto yep, it looks like I accidentally removed the part that made sure that you could hover from the icons to the links. It should be fixed now.

**Comment by leahcimto** [comment]
Reviewing now

**Review by leahcimto — APPROVED** [review]
@Accio1 Looking great now!

**Comment by gosoccerboy5** [comment]
If/when this gets merged, I can then make a PR that will probably fix #89 and also probably fix the problem I'm having.

**Comment by Accio1** [comment]
> If/when this gets merged, I can then make a PR that will probably fix #89 and also probably fix the problem I'm having.
> Question: when this gets merged, will I be able to easily update my fork with this new "fetch and merge" button, or will I have to manually update my fork and its branches?

I'm not sure what fetch and merge button you are talking about.

**Comment by Accio1** [comment]
> @Accio1 Looking great now!

Great! I just resolved the one merge conflict that was there, so I can merge now!

**Comment by leahcimto** [comment]
Awesome!

**Comment by leahcimto** [comment]
@Accio1 That's strange. I'll try it out on mine tomorrow morning as I'm going to go offline now. I'll let you know what happens.

**Comment by Accio1** [comment]
> @Accio1 That's strange. I'll try it out on mine tomorrow morning as I'm going to go offline now. I'll let you know what happens.

Alright, I'll try to do some research tonight as to why this is happening.

**Comment by leahcimto** [comment]
> > @Accio1 That's strange. I'll try it out on mine tomorrow morning as I'm going to go offline now. I'll let you know what happens.
> 
> Alright, I'll try to do some research tonight as to why this is happening.

@Accio1 The header on mobile is working fine for me.

GIF:
[https://ibb.co/W6bgZLh](https://ibb.co/W6bgZLh
)

**Comment by Accio1** [comment]
I just did a bit of research and apparently it is an iOS issue. I'll try to implement a fix later today.

**Comment by Accio1** [comment]
Hmm, I don't know then. I'll try a few things later to see if I can get it to work.

**Comment by Accio1** [comment]
This is more complex of an issue than I thought. I will likely have to use JavaScript to get it to work properly.

**Pull request merged**
