### PR TITLE
Fix CSS: Change Class Names | Part 1/4 of Fix CSS

### PR DESCRIPTION
**Pull request by leahcimto**
Changes class names both in the HTML documents and the stylesheet. Part one of fix css.

Please merge into a different branch than the master. Also, I tested this locally on my computer and it worked just fine.

cc: @Accio1

### CODE REVIEW

**Comment by MTM828** [comment]
I think we should remove the 'FHULink' class... like I did in my (deleted) fork.
Tincy wincy note: Would you like me to do something 3D with WebGL (I'll write it in Three.js) or something? Idk, it would make the site a lot cooler...

**Review by MTM828 — APPROVED** [review]

**Comment by Accio1** [comment]
@leahcimto I was reviewing this Pull Request and I changed my mind about some of the class names. I have changed them and will update the Fix CSS issue in order to reflect the changes that I have made.

If you are okay with the changes that I have made, I will merge this so that you can start working on part 2.

**Comment by leahcimto** [comment]
@Accio1 Changes look good 👍.

**Comment by Accio1** [comment]
@leahcimto I noticed that you wanted this to be merged to a branch other than master. There is no way for me to change which branch this PR merges into. Is it okay if I merge it into master instead?

**Comment by leahcimto** [comment]
@Accio1 that would be fine :)

**Comment by Accio1** [comment]
One more question before I merge this. What is a .DS_Store file and why did you commit one?

**Comment by leahcimto** [comment]
To be honest, I have no idea :P 
I think that was a thing with github desktop, because I can't find it in my finder and I never created it.

You can delete it as it has no content.

**Comment by MTM828** [comment]
> To be honest, I have no idea :P
> I think that was a thing with github desktop, because I can't find it in my finder and I never created it.
> 
> You can delete it as it has no content.

Ha ha, lol.

**Review by Accio1 — APPROVED** [review]
Looks good to merge! I tested this locally and all the pages looked the same as they did previous to these changes.

**Comment by Accio1** [comment]
Next Step: Take all inline styles and convert them into the stylesheet. Once again, don't worry about FHP.js, that will be addressed when the JavaScript is reworked. New classes/ids might need to be created in order to accommodate changing from inline to stylesheet CSS>

**Comment by leahcimto** [comment]
@Accio1 Created at #62 🎉

**Pull request merged**
