### PR TITLE
Lint styles

### LINKED ISSUE #161: Feature Request: Lint all the code
**Is your feature request related to a problem?**
the code is kinda messy and needs some linting

**Additional context**
please somebody make a PR that lints all the files

### LINKED ISSUE #199: Feature Request: Use consistent element IDs
**Is your feature request related to a problem?**
Yes - The ids created by FHP.js are not the nicest looking. They could be
ocular-${user}
instead of
Ocular${user}
**Describe alternatives you've considered**
None

**Additional context**
I could be assigned

### PR DESCRIPTION
**Pull request by FunctionalMetatable**
### Resolves:

Resolves #199
Resolves #161

### Changes:

Lints the stylesheet in the repository via [Prettier](https://github.com/prettier/prettier). Uses tabs (actually).
camelCase for every class & id.

### Tests:
Tested

### CODE REVIEW

**Comment by Accio1** [comment]
Ooh, I forgot to consider merge conflicts. Time to resolve those I guess!

**Comment by FunctionalMetatable** [comment]
I resolved the conflicts @Accio1!

**Comment by Accio1** [comment]
Looks good, but it looks like you forgot to change:
.nav_homeicon
.nav_title
.nav_button
.forumhelpers_navblock
.footer_content

**Comment by FunctionalMetatable** [comment]
> Looks good, but it looks like you forgot to change:
> .nav_homeicon
> .nav_title
> .nav_button
> .forumhelpers_navblock
> .footer_content

looks like I done all of them now

**Review by Accio1 — APPROVED** [review]
Looks good! Thanks for doing this!

**Pull request merged**
