### PR TITLE
New curators and bio updates

### LINKED ISSUE #78: Feature Request: Pending Curators To Be Added
Basic88
Nezon
moonliight--
NotDucki_
-InsanityGames-
bobcat0701
PoIygon
Steve0Greatness
-EmeraldThunder-
LankyBox01

Bios are pending for all users. I'll get them soon, and add these users to the list.

### PR DESCRIPTION
**Pull request by leahcimto**
Draft PR

Added new curators and bios updated. This PR is marked as a draft because I want to give curators time to send their bios in. At 6:30 PM EST, I'll mark it ready for review.

Closes #78

### CODE REVIEW

**Comment by leahcimto** [comment]
ah, sorry about vercel, I accidentally connected it to the wrong repo. just removed it.

**Comment by leahcimto** [comment]
No other bios were provided as of 6:35 PM EST.

**Comment by Accio1** [comment]
I don't appreciate Nezon's biography. It undermines the time and effort put into this site, as well as the fact that this site does have several purposes, and is therefore useful. If they have a problem with the site, they should leave an issue here, or a comment in the studio. They should not have a passive aggressive biography insulting the very site that the biography is hosted on. Therefore, I am removing it before merging this.

**Review by Accio1 — APPROVED** [review]
Looks good! I made the change that I mentioned above so this is good to merge!

**Pull request merged**
