### PR TITLE
Fix labels

### LINKED ISSUE #155: Bug: Labeler and Issue Templates Using Wrong Labels
**Describe the bug**
The labeler and issue templates are using the wrong labels as we recently changed them.

**To Reproduce**
1. make an issue/pr
2. notice that if you make an issue there will be no labels and if you make a pr it will make the labels.

**Expected behavior**
The issues and prs should be marked with the new labels

**Browser Information**
N/A

**Additional context**
None

### PR DESCRIPTION
**Pull request by leahcimto**
### Resolves:
Resolves #155 

Related to #164 

### Changes:
This pull request changes the issue templates by updating the labels and changing the labeler. It also improves the issue creation system with questions in the discussions tab and the option to create a general discussion. It also disables the blank issue template option and makes a blank issue template that assigns Accio1.

### Local Tests:
N/A. I used lots of things from ScratchAddons/ScratchAddons for the labeler and issue templates.

### CODE REVIEW

**Review by gosoccerboy5 — APPROVED** [review]
Looks good to me. 🙂 
Better than the April Fools PR, wouldn't want that!

**Comment by Accio1** [comment]
@leahcimto does this fix the actions labeller or just the issue templates?

**Comment by leahcimto** [comment]
@Accio1 Wait sorry no i forgot to copy those changes.

**Comment by leahcimto** [comment]
Now it should fix both.

**Pull request merged**
