### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by leahcimto**
### Resolves:

None. Just made this since it seems helpful.

### Changes:

This will automatically request Accio1 for review on all pull requests.

### Local Tests:

Not applicable

### CODE REVIEW

**Comment by Accio1** [comment]
@leahcimto I've added you as a codeowner for the /forumhelpers/managers.json and /forumhelpers/curators.json files. If you don't want to be a codeowner for those files, feel free to revert my changes and merge. Otherwise, you can go ahead and merge this.

**Review by Accio1 — APPROVED** [review]
@leahcimto I've added you as a codeowner for the /forumhelpers/managers.json and /forumhelpers/curators.json files. If you don't want to be a codeowner for those files, feel free to revert my changes and merge. Otherwise, you can go ahead and merge this.

**Comment by leahcimto** [comment]
> @leahcimto I've added you as a codeowner for the /forumhelpers/managers.json and /forumhelpers/curators.json files. If you don't want to be a codeowner for those files, feel free to revert my changes and merge. Otherwise, you can go ahead and merge this.

Ok, that's ok with me! Thanks! (I can't merge this though lol so pinging you @Accio1)

**Comment by Accio1** [comment]
> > @leahcimto I've added you as a codeowner for the /forumhelpers/managers.json and /forumhelpers/curators.json files. If you don't want to be a codeowner for those files, feel free to revert my changes and merge. Otherwise, you can go ahead and merge this.
> 
> Ok, that's ok with me! Thanks! (I can't merge this though lol so pinging you @Accio1)

Oh, that might be because admins are require to create CODEOWNERS files. Merging now!

**Comment by leahcimto** [comment]
> Oh, that might be because admins are require to create CODEOWNERS files. Merging now!

I don't normally have the option to merge since I am not authorized. Thanks for merging!

**Comment by Accio1** [comment]
Oh, I thought you could merge after I approved the changes. Thanks for letting me know!

**Pull request merged**
