### PR TITLE
Add TFH Dashboard Integration

### PR DESCRIPTION
**Pull request by Accio1**
Integrate applications page with The Forum Helpers Dashboard API.

### Resolves:

Doesn't resolve a specific issue, but @leahcimto and I discussed this and thought it would be a good idea.

### Changes:

Announcement about this coming soon!

### Local Tests:

Tested locally 

@leahcimto

### CODE REVIEW

**Comment by gosoccerboy5** [comment]
Pretty epic. How will you be changing the application status and codeword?

**Comment by Accio1** [comment]
> Pretty epic. How will you be changing the application status and codeword?

Stay tuned for an announcement after this is merged.

**Comment by gosoccerboy5** [comment]
ok

**Review by leahcimto — APPROVED** [review]
Looks great! I'm very excited for this new feature!

**Comment by Accio1** [comment]
See the announcement at #295 🥳

**Pull request merged**
